# Generated by Django 5.2.11 on 2026-03-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='point',
            new_name='name',
        ),
    ]
