server {
    listen 80;
    server_name pir8lab.me www.pir8lab.me;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name pir8lab.me www.pir8lab.me;

    ssl_certificate /etc/letsencrypt/live/pir8lab.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pir8lab.me/privkey.pem;

    location / {
        proxy_pass http://django-web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}