# Generated by Django 5.2.9 on 2026-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('start_node', models.CharField(max_length=100)),
                ('end_node', models.CharField(max_length=100)),
                ('current_node', models.CharField(max_length=100)),
                ('max_passengers', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
    ]
