# Generated by Django 5.2.9 on 2026-02-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_node', to='network.node'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='network.node'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='network.node'),
        ),
    ]
