# Generated by Django 5.2.9 on 2026-02-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_current_node_alter_trip_end_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_node',
        ),
    ]
