# Generated by Django 6.0.3 on 2026-03-23 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_created_by_alter_trip_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='booked_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_nodes', to='trips.trip'),
        ),
    ]
