# Generated by Django 6.0.2 on 2026-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_current_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
