# Generated by Django 6.0.3 on 2026-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_carpoolrequest_driveroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveroffer',
            name='detour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
