# Generated by Django 6.0.2 on 2026-02-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
