# Generated by Django 6.0.2 on 2026-02-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='driver',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='max_passengers',
        ),
    ]
